println("Branch name: ${BRANCH_NAME}")

switch(BRANCH_NAME) {
  case "test.deploy":
    aws_region="us-east-1"
    region="info"
    cloud_front_distribution_id="E3DCOH2ZTE42J5"
    site_url="https://testnew-helpcenter.onlyoffice.com/" 
    cms="https://cmshelpcenter.teamlab.info"
    appServer="https://testnew-helpcenter.onlyoffice.com/"
    preview_url="https://testnew-helpcenter.onlyoffice.com/api/preview"
    main_site_base_domain="https://test-new.teamlab.info"
    algolia_index="test_ARTICLES"
    break
  case "production.deploy":
    aws_region="us-east-1"
    region="com"
    MONITOR_ID = '8888888888888'
    cloud_front_distribution_id="E2E2PQUBA1BLDR"
    site_url="https://prodnew-helpcenter.onlyoffice.com/"
    cms="https://cmshelpcenter.onlyoffice.com"
    appServer="https://prodnew-helpcenter.onlyoffice.com/"
    preview_url="https://helpcenter.onlyoffice.com/api/preview"
    main_site_base_domain="https://onlyoffice.com"
    algolia_index="prod_ARTICLES"
    break
  default:
    println("Branch: ${BRANCH_NAME} do not for deploy.")
    break
}

pipeline {
  agent { label 'ubuntu' }
  triggers {
    githubPush()
  }
  options {
    disableConcurrentBuilds()
    buildDiscarder (logRotator(numToKeepStr: '50', artifactNumToKeepStr: '5'))
  }
  stages {
    stage('stop_monitor') {
      when { branch 'production_deploy111' }
      steps {
        build job: 'monitor.24x7.start.stop', 
          parameters: [string(name: 'monitor_id', value: "${MONITOR_ID}"), 
          string(name: 'action', value: 'suspend')]
      }    
    }
    
    stage('deploy') {
      when { 
        anyOf { branch 'test.deploy';
                branch 'production.deploy' }
      }
      environment {
        region = "${region}"
        cms="${cms}"
        appServer="${appServer}"
        preview_url="${preview_url}"
        site_url="${site_url}"
        main_site_base_domain = "${main_site_base_domain}"
        algolia_index = "${algolia_index}"
      }
      steps {
        withCredentials([
                string(credentialsId: 'cms_helpcenter_test_preview_secret', variable: 'cms_helpcenter_test_preview_secret'),
                string(credentialsId: 'cms_helpcenter_prod_preview_secret', variable: 'cms_helpcenter_prod_preview_secret'),
                string(credentialsId: 'helpcenter_prod_algolia_app_id', variable: 'helpcenter_prod_algolia_app_id'),
                string(credentialsId: 'helpcenter_test_algolia_app_id', variable: 'helpcenter_test_algolia_app_id'),
                string(credentialsId: 'helpcenter_test_algolia_search_key', variable: 'helpcenter_test_algolia_search_key'),
                string(credentialsId: 'helpcenter_prod_algolia_search_key', variable: 'helpcenter_prod_algolia_search_key'),
                string(credentialsId: 'helpcenter_prod_algolia_assistant_id', variable: 'helpcenter_prod_algolia_assistant_id'),
                string(credentialsId: 'helpcenter_test_algolia_assistant_id', variable: 'helpcenter_test_algolia_assistant_id'),
                string(credentialsId: 'helpcenter_test_algolia_admin_key', variable: 'helpcenter_test_algolia_admin_key'),
                string(credentialsId: 'helpcenter_prod_algolia_admin_key', variable: 'helpcenter_prod_algolia_admin_key')
                        ]) {
        sh '''

          sed -i "s^var_notification_app_name^$site_url^" .jenkins/build.sh
          cp .jenkins/build.sh .jenkins/helpcenter_build.sh
          mv .env.example .env
        
          sed -i "s^config_cms^$cms^" config/config.json
          sed -i "s^config_appServer^$appServer^" config/config.json
          sed -i "s^preview_url_placeholder^$preview_url^" config/config.json
          sed -i "s^var_main_site_base_domain^$main_site_base_domain^" .env
          sed -i "s^var_algolia_index_name^$algolia_index^" .env

          if [[ "$region" == "com" ]]; then
            sed -i "s^preview_secret_key^$cms_helpcenter_prod_preview_secret^" config/config.json
            sed -i "s^var_algolia_app_id^$helpcenter_prod_algolia_app_id^" .env
            sed -i "s^var_algolia_search_key^$helpcenter_prod_algolia_search_key^" .env
            sed -i "s^var_algolia_assistant_id^$helpcenter_prod_algolia_assistant_id^" .env
            sed -i "s^var_algolia_admin_key^$helpcenter_prod_algolia_admin_key^" .env
          else
            sed -i "s^preview_secret_key^$cms_helpcenter_test_preview_secret^" config/config.json
            sed -i "s^var_algolia_app_id^$helpcenter_test_algolia_app_id^" .env
            sed -i "s^var_algolia_search_key^$helpcenter_test_algolia_search_key^" .env
            sed -i "s^var_algolia_assistant_id^$helpcenter_test_algolia_assistant_id^" .env
            sed -i "s^var_algolia_admin_key^$helpcenter_test_algolia_admin_key^" .env
            cp .jenkins/robots.txt ./
          fi

          if [ "${region}" = "info" ]; then
            cp .jenkins/robots.txt ./
          fi

          tar -czpf .jenkins/helpcenter.tar.gz \
            --exclude ".git" \
            --exclude ".gitignore" \
            --exclude ".jenkins" \
            --exclude "README.md" .
          
          echo "Deploy from ${BRANCH_NAME} is starting."
        '''
        
        sshPublisher(publishers: [sshPublisherDesc(configName: "sites2026@${region}", 
          transfers: [sshTransfer(cleanRemote: false, 
            excludes: '', 
            execCommand: '''
              sudo bash /home/ubuntu/deploy/.jenkins/helpcenter_build.sh |& tee -a > /home/ubuntu/deploy/helpcenter_deploy.log
            ''', 
            execTimeout: 600000, 
            flatten: false, 
            makeEmptyDirs: false, 
            noDefaultExcludes: false, 
            patternSeparator: '[, ]+', 
            remoteDirectory: '', 
            remoteDirectorySDF: false, 
            removePrefix: '', 
            sourceFiles: '.jenkins/helpcenter.tar.gz,.jenkins/helpcenter_build.sh')], 
          usePromotionTimestamp: false, 
          useWorkspaceInPromotion: false, 
          verbose: false)])
      }
      }
    }
    stage('invalidation') {
      when { 
        anyOf { branch 'test.deploy';
                branch 'production.deploy' }
      }
      environment {
        aws_region = "${aws_region}"
        cloud_front_distribution_id = "${cloud_front_distribution_id}"
      }
      steps {
        withCredentials([
                usernamePassword(credentialsId: 'aws_build_robot', 
                passwordVariable: 'secret_key', 
                usernameVariable: 'access_key')]) {
          sh '''
            export AWS_ACCESS_KEY_ID="$access_key"
            export AWS_SECRET_ACCESS_KEY="$secret_key"
            export AWS_DEFAULT_aws_region="$aws_region"
            
            echo "=== start invalidation ==="
            aws cloudfront create-invalidation --distribution-id ${cloud_front_distribution_id} --paths "/*" || \
            aws cloudfront create-invalidation --distribution-id ${cloud_front_distribution_id} --paths "/*"
          '''
        }
      }
    }
    
    stage('start_monitor') {
      when { branch 'production_deploy111' }
      steps {
        build job: 'monitor.24x7.start.stop', 
          parameters: [string(name: 'monitor_id', value: "${MONITOR_ID}"), 
          string(name: 'action', value: 'activate')]
      }    
    }
  }
}
